version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: bead-pattern-wp
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_DEBUG_LOG: 'true'
      WORDPRESS_DEBUG_DISPLAY: 'false'
    volumes:
      - wordpress_data:/var/www/html
      - ./bead-pattern-designer:/var/www/html/wp-content/plugins/bead-pattern-designer
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    container_name: bead-pattern-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
      MYSQL_ROOT_PASSWORD: rootpassword123
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bead-pattern-pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword123
    depends_on:
      - db
    restart: always

volumes:
  wordpress_data:
  db_data: